// Code generated by go-swagger; DO NOT EDIT.

package buckets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// GetBucketReader is a Reader for the GetBucket structure.
type GetBucketReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBucketReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBucketOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetBucketDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetBucketOK creates a GetBucketOK with default headers values
func NewGetBucketOK() *GetBucketOK {
	return &GetBucketOK{}
}

/*GetBucketOK handles this case with default header values.

GetBucketOK get bucket o k
*/
type GetBucketOK struct {
	Payload *GetBucketOKBody
}

func (o *GetBucketOK) Error() string {
	return fmt.Sprintf("[GET /storage/v1/stacks/{stack_id}/buckets/{bucket_id}][%d] getBucketOK  %+v", 200, o.Payload)
}

func (o *GetBucketOK) GetPayload() *GetBucketOKBody {
	return o.Payload
}

func (o *GetBucketOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetBucketOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBucketDefault creates a GetBucketDefault with default headers values
func NewGetBucketDefault(code int) *GetBucketDefault {
	return &GetBucketDefault{
		_statusCode: code,
	}
}

/*GetBucketDefault handles this case with default header values.

Default error structure.
*/
type GetBucketDefault struct {
	_statusCode int

	Payload *GetBucketDefaultBody
}

// Code gets the status code for the get bucket default response
func (o *GetBucketDefault) Code() int {
	return o._statusCode
}

func (o *GetBucketDefault) Error() string {
	return fmt.Sprintf("[GET /storage/v1/stacks/{stack_id}/buckets/{bucket_id}][%d] GetBucket default  %+v", o._statusCode, o.Payload)
}

func (o *GetBucketDefault) GetPayload() *GetBucketDefaultBody {
	return o.Payload
}

func (o *GetBucketDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetBucketDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetBucketDefaultBody get bucket default body
swagger:model GetBucketDefaultBody
*/
type GetBucketDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get bucket default body
func (o *GetBucketDefaultBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetBucketDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBucketDefaultBody) UnmarshalBinary(b []byte) error {
	var res GetBucketDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetBucketOKBody The bucket for the given stack
swagger:model GetBucketOKBody
*/
type GetBucketOKBody struct {

	// bucket
	Bucket *GetBucketOKBodyBucket `json:"bucket,omitempty"`
}

// Validate validates this get bucket o k body
func (o *GetBucketOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBucket(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBucketOKBody) validateBucket(formats strfmt.Registry) error {

	if swag.IsZero(o.Bucket) { // not required
		return nil
	}

	if o.Bucket != nil {
		if err := o.Bucket.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getBucketOK" + "." + "bucket")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBucketOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBucketOKBody) UnmarshalBinary(b []byte) error {
	var res GetBucketOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetBucketOKBodyBucket get bucket o k body bucket
swagger:model GetBucketOKBodyBucket
*/
type GetBucketOKBodyBucket struct {

	// The date when the bucket was created
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"createdAt,omitempty"`

	// The URL used to access the bucket
	EndpointURL string `json:"endpointUrl,omitempty"`

	// The ID for the bucket
	ID string `json:"id,omitempty"`

	// The name of the bucket
	Label string `json:"label,omitempty"`

	// The region in which the bucket is created. Available regions are: us-east-1, us-west-1, eu-central-1
	Region string `json:"region,omitempty"`

	// The date when the bucket was last updated
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updatedAt,omitempty"`

	// - PRIVATE: The bucket is private and only accessibly with credentials
	//  - PUBLIC: The bucket is public and accessible over the internet
	// Enum: [PRIVATE PUBLIC]
	Visibility *string `json:"visibility,omitempty"`
}

// Validate validates this get bucket o k body bucket
func (o *GetBucketOKBodyBucket) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVisibility(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBucketOKBodyBucket) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(o.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("getBucketOK"+"."+"bucket"+"."+"createdAt", "body", "date-time", o.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetBucketOKBodyBucket) validateUpdatedAt(formats strfmt.Registry) error {

	if swag.IsZero(o.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("getBucketOK"+"."+"bucket"+"."+"updatedAt", "body", "date-time", o.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var getBucketOKBodyBucketTypeVisibilityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PRIVATE","PUBLIC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getBucketOKBodyBucketTypeVisibilityPropEnum = append(getBucketOKBodyBucketTypeVisibilityPropEnum, v)
	}
}

const (

	// GetBucketOKBodyBucketVisibilityPRIVATE captures enum value "PRIVATE"
	GetBucketOKBodyBucketVisibilityPRIVATE string = "PRIVATE"

	// GetBucketOKBodyBucketVisibilityPUBLIC captures enum value "PUBLIC"
	GetBucketOKBodyBucketVisibilityPUBLIC string = "PUBLIC"
)

// prop value enum
func (o *GetBucketOKBodyBucket) validateVisibilityEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, getBucketOKBodyBucketTypeVisibilityPropEnum); err != nil {
		return err
	}
	return nil
}

func (o *GetBucketOKBodyBucket) validateVisibility(formats strfmt.Registry) error {

	if swag.IsZero(o.Visibility) { // not required
		return nil
	}

	// value enum
	if err := o.validateVisibilityEnum("getBucketOK"+"."+"bucket"+"."+"visibility", "body", *o.Visibility); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBucketOKBodyBucket) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBucketOKBodyBucket) UnmarshalBinary(b []byte) error {
	var res GetBucketOKBodyBucket
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
