// Code generated by go-swagger; DO NOT EDIT.

package virtual_machine_images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stackpath/terraform-provider-stackpath/v2/stackpath/api/workload/workload_models"
)

// DeleteImagesForFamilyReader is a Reader for the DeleteImagesForFamily structure.
type DeleteImagesForFamilyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteImagesForFamilyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteImagesForFamilyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteImagesForFamilyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteImagesForFamilyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteImagesForFamilyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteImagesForFamilyNoContent creates a DeleteImagesForFamilyNoContent with default headers values
func NewDeleteImagesForFamilyNoContent() *DeleteImagesForFamilyNoContent {
	return &DeleteImagesForFamilyNoContent{}
}

/*
DeleteImagesForFamilyNoContent describes a response with status code 204, with default header values.

No content
*/
type DeleteImagesForFamilyNoContent struct {
}

func (o *DeleteImagesForFamilyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyNoContent ", 204)
}

func (o *DeleteImagesForFamilyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteImagesForFamilyUnauthorized creates a DeleteImagesForFamilyUnauthorized with default headers values
func NewDeleteImagesForFamilyUnauthorized() *DeleteImagesForFamilyUnauthorized {
	return &DeleteImagesForFamilyUnauthorized{}
}

/*
DeleteImagesForFamilyUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type DeleteImagesForFamilyUnauthorized struct {
	Payload *workload_models.StackpathapiStatus
}

func (o *DeleteImagesForFamilyUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteImagesForFamilyUnauthorized) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImagesForFamilyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImagesForFamilyInternalServerError creates a DeleteImagesForFamilyInternalServerError with default headers values
func NewDeleteImagesForFamilyInternalServerError() *DeleteImagesForFamilyInternalServerError {
	return &DeleteImagesForFamilyInternalServerError{}
}

/*
DeleteImagesForFamilyInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteImagesForFamilyInternalServerError struct {
	Payload *workload_models.StackpathapiStatus
}

func (o *DeleteImagesForFamilyInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] deleteImagesForFamilyInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteImagesForFamilyInternalServerError) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImagesForFamilyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImagesForFamilyDefault creates a DeleteImagesForFamilyDefault with default headers values
func NewDeleteImagesForFamilyDefault(code int) *DeleteImagesForFamilyDefault {
	return &DeleteImagesForFamilyDefault{
		_statusCode: code,
	}
}

/*
DeleteImagesForFamilyDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type DeleteImagesForFamilyDefault struct {
	_statusCode int

	Payload *workload_models.StackpathapiStatus
}

// Code gets the status code for the delete images for family default response
func (o *DeleteImagesForFamilyDefault) Code() int {
	return o._statusCode
}

func (o *DeleteImagesForFamilyDefault) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}][%d] DeleteImagesForFamily default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteImagesForFamilyDefault) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImagesForFamilyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
