// Code generated by go-swagger; DO NOT EDIT.

package virtual_machine_images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stackpath/terraform-provider-stackpath/v2/stackpath/api/workload/workload_models"
)

// DeleteImageReader is a Reader for the DeleteImage structure.
type DeleteImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteImageNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteImageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteImageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteImageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteImageNoContent creates a DeleteImageNoContent with default headers values
func NewDeleteImageNoContent() *DeleteImageNoContent {
	return &DeleteImageNoContent{}
}

/*
DeleteImageNoContent describes a response with status code 204, with default header values.

No content
*/
type DeleteImageNoContent struct {
}

func (o *DeleteImageNoContent) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}/{image_tag}][%d] deleteImageNoContent ", 204)
}

func (o *DeleteImageNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteImageUnauthorized creates a DeleteImageUnauthorized with default headers values
func NewDeleteImageUnauthorized() *DeleteImageUnauthorized {
	return &DeleteImageUnauthorized{}
}

/*
DeleteImageUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type DeleteImageUnauthorized struct {
	Payload *workload_models.StackpathapiStatus
}

func (o *DeleteImageUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}/{image_tag}][%d] deleteImageUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteImageUnauthorized) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImageInternalServerError creates a DeleteImageInternalServerError with default headers values
func NewDeleteImageInternalServerError() *DeleteImageInternalServerError {
	return &DeleteImageInternalServerError{}
}

/*
DeleteImageInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteImageInternalServerError struct {
	Payload *workload_models.StackpathapiStatus
}

func (o *DeleteImageInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}/{image_tag}][%d] deleteImageInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteImageInternalServerError) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteImageDefault creates a DeleteImageDefault with default headers values
func NewDeleteImageDefault(code int) *DeleteImageDefault {
	return &DeleteImageDefault{
		_statusCode: code,
	}
}

/*
DeleteImageDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type DeleteImageDefault struct {
	_statusCode int

	Payload *workload_models.StackpathapiStatus
}

// Code gets the status code for the delete image default response
func (o *DeleteImageDefault) Code() int {
	return o._statusCode
}

func (o *DeleteImageDefault) Error() string {
	return fmt.Sprintf("[DELETE /workload/v1/stacks/{stack_id}/images/{image_family}/{image_tag}][%d] DeleteImage default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteImageDefault) GetPayload() *workload_models.StackpathapiStatus {
	return o.Payload
}

func (o *DeleteImageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(workload_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
