// Code generated by go-swagger; DO NOT EDIT.

package ipam_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetworkNetwork A network defined within a Virtual Private Cloud
//
// swagger:model networkNetwork
type NetworkNetwork struct {

	// A network's unique identifier
	ID string `json:"id,omitempty"`

	// ip families
	IPFamilies []string `json:"ipFamilies"`

	// ipv6 subnet
	IPV6Subnet string `json:"ipv6Subnet,omitempty"`

	// metadata
	Metadata *NetworkMetadata `json:"metadata,omitempty"`

	// A network's human-readable name
	Name string `json:"name,omitempty"`

	// A subnet identifier and network mask in CIDR notation format
	//
	// A network's root subnet is its primary subnet.
	RootSubnet string `json:"rootSubnet,omitempty"`

	// A network's machine-readable name
	Slug string `json:"slug,omitempty"`

	// The ID of the stack that a network belongs to
	StackID string `json:"stackId,omitempty"`

	// A network's VLAN identifier
	VirtualNetworkIdentifier int32 `json:"virtualNetworkIdentifier,omitempty"`
}

// Validate validates this network network
func (m *NetworkNetwork) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NetworkNetwork) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this network network based on the context it is used
func (m *NetworkNetwork) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NetworkNetwork) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {
		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NetworkNetwork) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkNetwork) UnmarshalBinary(b []byte) error {
	var res NetworkNetwork
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
