// Code generated by go-swagger; DO NOT EDIT.

package ipam_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1ProtocolIcmp ICMP protocol matching
//
// swagger:model v1ProtocolIcmp
type V1ProtocolIcmp struct{}
