// Code generated by go-swagger; DO NOT EDIT.

package ipam_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Protocols An object of all supported protocols and any attributes for them
// swagger:model v1Protocols
type V1Protocols struct {

	// ah
	Ah *V1ProtocolAh `json:"ah,omitempty"`

	// esp
	Esp *V1ProtocolEsp `json:"esp,omitempty"`

	// gre
	Gre *V1ProtocolGre `json:"gre,omitempty"`

	// icmp
	Icmp *V1ProtocolIcmp `json:"icmp,omitempty"`

	// tcp
	TCP *V1ProtocolTCP `json:"tcp,omitempty"`

	// tcp Udp
	TCPUDP *V1ProtocolTCPUDP `json:"tcpUdp,omitempty"`

	// udp
	UDP *V1ProtocolUDP `json:"udp,omitempty"`
}

// Validate validates this v1 protocols
func (m *V1Protocols) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTCP(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTCPUDP(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUDP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Protocols) validateTCP(formats strfmt.Registry) error {

	if swag.IsZero(m.TCP) { // not required
		return nil
	}

	if m.TCP != nil {
		if err := m.TCP.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tcp")
			}
			return err
		}
	}

	return nil
}

func (m *V1Protocols) validateTCPUDP(formats strfmt.Registry) error {

	if swag.IsZero(m.TCPUDP) { // not required
		return nil
	}

	if m.TCPUDP != nil {
		if err := m.TCPUDP.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tcpUdp")
			}
			return err
		}
	}

	return nil
}

func (m *V1Protocols) validateUDP(formats strfmt.Registry) error {

	if swag.IsZero(m.UDP) { // not required
		return nil
	}

	if m.UDP != nil {
		if err := m.UDP.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("udp")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1Protocols) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Protocols) UnmarshalBinary(b []byte) error {
	var res V1Protocols
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
