// Code generated by go-swagger; DO NOT EDIT.

package ipam_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1ProtocolIpip IP-within-IP Encapsulation (IPIP) protocol matching
//
// swagger:model v1ProtocolIpip
type V1ProtocolIpip struct{}
