// Code generated by go-swagger; DO NOT EDIT.

package ipam_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1ProtocolEsp Encapsulating Security Payload (ESP) protocol matching
// swagger:model v1ProtocolEsp
type V1ProtocolEsp struct{}
