// Code generated by go-swagger; DO NOT EDIT.

package user_credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stackpath/terraform-provider-stackpath/v2/stackpath/api/storage/storage_models"
)

// GetCredentialsReader is a Reader for the GetCredentials structure.
type GetCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCredentialsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCredentialsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCredentialsOK creates a GetCredentialsOK with default headers values
func NewGetCredentialsOK() *GetCredentialsOK {
	return &GetCredentialsOK{}
}

/* GetCredentialsOK describes a response with status code 200, with default header values.

GetCredentialsOK get credentials o k
*/
type GetCredentialsOK struct {
	Payload *storage_models.StorageGetCredentialsResponse
}

func (o *GetCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /storage/v1/stacks/{stack_id}/users/{user_id}/credentials][%d] getCredentialsOK  %+v", 200, o.Payload)
}
func (o *GetCredentialsOK) GetPayload() *storage_models.StorageGetCredentialsResponse {
	return o.Payload
}

func (o *GetCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(storage_models.StorageGetCredentialsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCredentialsUnauthorized creates a GetCredentialsUnauthorized with default headers values
func NewGetCredentialsUnauthorized() *GetCredentialsUnauthorized {
	return &GetCredentialsUnauthorized{}
}

/* GetCredentialsUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type GetCredentialsUnauthorized struct {
	Payload *storage_models.StackpathapiStatus
}

func (o *GetCredentialsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /storage/v1/stacks/{stack_id}/users/{user_id}/credentials][%d] getCredentialsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetCredentialsUnauthorized) GetPayload() *storage_models.StackpathapiStatus {
	return o.Payload
}

func (o *GetCredentialsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(storage_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCredentialsInternalServerError creates a GetCredentialsInternalServerError with default headers values
func NewGetCredentialsInternalServerError() *GetCredentialsInternalServerError {
	return &GetCredentialsInternalServerError{}
}

/* GetCredentialsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetCredentialsInternalServerError struct {
	Payload *storage_models.StackpathapiStatus
}

func (o *GetCredentialsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /storage/v1/stacks/{stack_id}/users/{user_id}/credentials][%d] getCredentialsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetCredentialsInternalServerError) GetPayload() *storage_models.StackpathapiStatus {
	return o.Payload
}

func (o *GetCredentialsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(storage_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCredentialsDefault creates a GetCredentialsDefault with default headers values
func NewGetCredentialsDefault(code int) *GetCredentialsDefault {
	return &GetCredentialsDefault{
		_statusCode: code,
	}
}

/* GetCredentialsDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type GetCredentialsDefault struct {
	_statusCode int

	Payload *storage_models.StackpathapiStatus
}

// Code gets the status code for the get credentials default response
func (o *GetCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *GetCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /storage/v1/stacks/{stack_id}/users/{user_id}/credentials][%d] GetCredentials default  %+v", o._statusCode, o.Payload)
}
func (o *GetCredentialsDefault) GetPayload() *storage_models.StackpathapiStatus {
	return o.Payload
}

func (o *GetCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(storage_models.StackpathapiStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
