// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// StackpathRPCRetryInfoAllOf1 stackpath Rpc retry info all of1
// swagger:model stackpathRpcRetryInfoAllOf1
type StackpathRPCRetryInfoAllOf1 struct {

	// retry delay
	RetryDelay string `json:"retryDelay,omitempty"`
}

// Validate validates this stackpath Rpc retry info all of1
func (m *StackpathRPCRetryInfoAllOf1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StackpathRPCRetryInfoAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StackpathRPCRetryInfoAllOf1) UnmarshalBinary(b []byte) error {
	var res StackpathRPCRetryInfoAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
