// Code generated by go-swagger; DO NOT EDIT.

package virtual_private_cloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/stackpath/terraform-provider-stackpath/v2/stackpath/api/ipam/ipam_models"
)

// GetNetworkSubnetsReader is a Reader for the GetNetworkSubnets structure.
type GetNetworkSubnetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkSubnetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkSubnetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetNetworkSubnetsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNetworkSubnetsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetNetworkSubnetsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetNetworkSubnetsOK creates a GetNetworkSubnetsOK with default headers values
func NewGetNetworkSubnetsOK() *GetNetworkSubnetsOK {
	return &GetNetworkSubnetsOK{}
}

/* GetNetworkSubnetsOK describes a response with status code 200, with default header values.

GetNetworkSubnetsOK get network subnets o k
*/
type GetNetworkSubnetsOK struct {
	Payload *ipam_models.NetworkGetNetworkSubnetsResponse
}

func (o *GetNetworkSubnetsOK) Error() string {
	return fmt.Sprintf("[GET /ipam/v1alpha/stacks/{stack_id}/networks/{network_id}/subnets][%d] getNetworkSubnetsOK  %+v", 200, o.Payload)
}
func (o *GetNetworkSubnetsOK) GetPayload() *ipam_models.NetworkGetNetworkSubnetsResponse {
	return o.Payload
}

func (o *GetNetworkSubnetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ipam_models.NetworkGetNetworkSubnetsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworkSubnetsUnauthorized creates a GetNetworkSubnetsUnauthorized with default headers values
func NewGetNetworkSubnetsUnauthorized() *GetNetworkSubnetsUnauthorized {
	return &GetNetworkSubnetsUnauthorized{}
}

/* GetNetworkSubnetsUnauthorized describes a response with status code 401, with default header values.

Returned when an unauthorized request is attempted.
*/
type GetNetworkSubnetsUnauthorized struct {
	Payload *ipam_models.APIStatus
}

func (o *GetNetworkSubnetsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /ipam/v1alpha/stacks/{stack_id}/networks/{network_id}/subnets][%d] getNetworkSubnetsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetNetworkSubnetsUnauthorized) GetPayload() *ipam_models.APIStatus {
	return o.Payload
}

func (o *GetNetworkSubnetsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ipam_models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworkSubnetsInternalServerError creates a GetNetworkSubnetsInternalServerError with default headers values
func NewGetNetworkSubnetsInternalServerError() *GetNetworkSubnetsInternalServerError {
	return &GetNetworkSubnetsInternalServerError{}
}

/* GetNetworkSubnetsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetNetworkSubnetsInternalServerError struct {
	Payload *ipam_models.APIStatus
}

func (o *GetNetworkSubnetsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /ipam/v1alpha/stacks/{stack_id}/networks/{network_id}/subnets][%d] getNetworkSubnetsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetNetworkSubnetsInternalServerError) GetPayload() *ipam_models.APIStatus {
	return o.Payload
}

func (o *GetNetworkSubnetsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ipam_models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworkSubnetsDefault creates a GetNetworkSubnetsDefault with default headers values
func NewGetNetworkSubnetsDefault(code int) *GetNetworkSubnetsDefault {
	return &GetNetworkSubnetsDefault{
		_statusCode: code,
	}
}

/* GetNetworkSubnetsDefault describes a response with status code -1, with default header values.

Default error structure.
*/
type GetNetworkSubnetsDefault struct {
	_statusCode int

	Payload *ipam_models.APIStatus
}

// Code gets the status code for the get network subnets default response
func (o *GetNetworkSubnetsDefault) Code() int {
	return o._statusCode
}

func (o *GetNetworkSubnetsDefault) Error() string {
	return fmt.Sprintf("[GET /ipam/v1alpha/stacks/{stack_id}/networks/{network_id}/subnets][%d] GetNetworkSubnets default  %+v", o._statusCode, o.Payload)
}
func (o *GetNetworkSubnetsDefault) GetPayload() *ipam_models.APIStatus {
	return o.Payload
}

func (o *GetNetworkSubnetsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ipam_models.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
