// Code generated by go-swagger; DO NOT EDIT.

package virtual_private_cloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkSubnetParams creates a new GetNetworkSubnetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkSubnetParams() *GetNetworkSubnetParams {
	return &GetNetworkSubnetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkSubnetParamsWithTimeout creates a new GetNetworkSubnetParams object
// with the ability to set a timeout on a request.
func NewGetNetworkSubnetParamsWithTimeout(timeout time.Duration) *GetNetworkSubnetParams {
	return &GetNetworkSubnetParams{
		timeout: timeout,
	}
}

// NewGetNetworkSubnetParamsWithContext creates a new GetNetworkSubnetParams object
// with the ability to set a context for a request.
func NewGetNetworkSubnetParamsWithContext(ctx context.Context) *GetNetworkSubnetParams {
	return &GetNetworkSubnetParams{
		Context: ctx,
	}
}

// NewGetNetworkSubnetParamsWithHTTPClient creates a new GetNetworkSubnetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkSubnetParamsWithHTTPClient(client *http.Client) *GetNetworkSubnetParams {
	return &GetNetworkSubnetParams{
		HTTPClient: client,
	}
}

/* GetNetworkSubnetParams contains all the parameters to send to the API endpoint
   for the get network subnet operation.

   Typically these are written to a http.Request.
*/
type GetNetworkSubnetParams struct {

	// NetworkID.
	NetworkID string

	// StackID.
	StackID string

	// SubnetID.
	SubnetID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkSubnetParams) WithDefaults() *GetNetworkSubnetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkSubnetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network subnet params
func (o *GetNetworkSubnetParams) WithTimeout(timeout time.Duration) *GetNetworkSubnetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network subnet params
func (o *GetNetworkSubnetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network subnet params
func (o *GetNetworkSubnetParams) WithContext(ctx context.Context) *GetNetworkSubnetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network subnet params
func (o *GetNetworkSubnetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network subnet params
func (o *GetNetworkSubnetParams) WithHTTPClient(client *http.Client) *GetNetworkSubnetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network subnet params
func (o *GetNetworkSubnetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network subnet params
func (o *GetNetworkSubnetParams) WithNetworkID(networkID string) *GetNetworkSubnetParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network subnet params
func (o *GetNetworkSubnetParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithStackID adds the stackID to the get network subnet params
func (o *GetNetworkSubnetParams) WithStackID(stackID string) *GetNetworkSubnetParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get network subnet params
func (o *GetNetworkSubnetParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WithSubnetID adds the subnetID to the get network subnet params
func (o *GetNetworkSubnetParams) WithSubnetID(subnetID string) *GetNetworkSubnetParams {
	o.SetSubnetID(subnetID)
	return o
}

// SetSubnetID adds the subnetId to the get network subnet params
func (o *GetNetworkSubnetParams) SetSubnetID(subnetID string) {
	o.SubnetID = subnetID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkSubnetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	// path param subnet_id
	if err := r.SetPathParam("subnet_id", o.SubnetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
