// Code generated by go-swagger; DO NOT EDIT.

package virtual_private_cloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkSubnetsParams creates a new GetNetworkSubnetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkSubnetsParams() *GetNetworkSubnetsParams {
	return &GetNetworkSubnetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkSubnetsParamsWithTimeout creates a new GetNetworkSubnetsParams object
// with the ability to set a timeout on a request.
func NewGetNetworkSubnetsParamsWithTimeout(timeout time.Duration) *GetNetworkSubnetsParams {
	return &GetNetworkSubnetsParams{
		timeout: timeout,
	}
}

// NewGetNetworkSubnetsParamsWithContext creates a new GetNetworkSubnetsParams object
// with the ability to set a context for a request.
func NewGetNetworkSubnetsParamsWithContext(ctx context.Context) *GetNetworkSubnetsParams {
	return &GetNetworkSubnetsParams{
		Context: ctx,
	}
}

// NewGetNetworkSubnetsParamsWithHTTPClient creates a new GetNetworkSubnetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkSubnetsParamsWithHTTPClient(client *http.Client) *GetNetworkSubnetsParams {
	return &GetNetworkSubnetsParams{
		HTTPClient: client,
	}
}

/* GetNetworkSubnetsParams contains all the parameters to send to the API endpoint
   for the get network subnets operation.

   Typically these are written to a http.Request.
*/
type GetNetworkSubnetsParams struct {

	// NetworkID.
	NetworkID string

	// PageRequestAfter.
	PageRequestAfter *string

	// PageRequestFilter.
	PageRequestFilter *string

	// PageRequestFirst.
	PageRequestFirst *string

	// PageRequestSortBy.
	PageRequestSortBy *string

	// StackID.
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network subnets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkSubnetsParams) WithDefaults() *GetNetworkSubnetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network subnets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkSubnetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network subnets params
func (o *GetNetworkSubnetsParams) WithTimeout(timeout time.Duration) *GetNetworkSubnetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network subnets params
func (o *GetNetworkSubnetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network subnets params
func (o *GetNetworkSubnetsParams) WithContext(ctx context.Context) *GetNetworkSubnetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network subnets params
func (o *GetNetworkSubnetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network subnets params
func (o *GetNetworkSubnetsParams) WithHTTPClient(client *http.Client) *GetNetworkSubnetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network subnets params
func (o *GetNetworkSubnetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network subnets params
func (o *GetNetworkSubnetsParams) WithNetworkID(networkID string) *GetNetworkSubnetsParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network subnets params
func (o *GetNetworkSubnetsParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithPageRequestAfter adds the pageRequestAfter to the get network subnets params
func (o *GetNetworkSubnetsParams) WithPageRequestAfter(pageRequestAfter *string) *GetNetworkSubnetsParams {
	o.SetPageRequestAfter(pageRequestAfter)
	return o
}

// SetPageRequestAfter adds the pageRequestAfter to the get network subnets params
func (o *GetNetworkSubnetsParams) SetPageRequestAfter(pageRequestAfter *string) {
	o.PageRequestAfter = pageRequestAfter
}

// WithPageRequestFilter adds the pageRequestFilter to the get network subnets params
func (o *GetNetworkSubnetsParams) WithPageRequestFilter(pageRequestFilter *string) *GetNetworkSubnetsParams {
	o.SetPageRequestFilter(pageRequestFilter)
	return o
}

// SetPageRequestFilter adds the pageRequestFilter to the get network subnets params
func (o *GetNetworkSubnetsParams) SetPageRequestFilter(pageRequestFilter *string) {
	o.PageRequestFilter = pageRequestFilter
}

// WithPageRequestFirst adds the pageRequestFirst to the get network subnets params
func (o *GetNetworkSubnetsParams) WithPageRequestFirst(pageRequestFirst *string) *GetNetworkSubnetsParams {
	o.SetPageRequestFirst(pageRequestFirst)
	return o
}

// SetPageRequestFirst adds the pageRequestFirst to the get network subnets params
func (o *GetNetworkSubnetsParams) SetPageRequestFirst(pageRequestFirst *string) {
	o.PageRequestFirst = pageRequestFirst
}

// WithPageRequestSortBy adds the pageRequestSortBy to the get network subnets params
func (o *GetNetworkSubnetsParams) WithPageRequestSortBy(pageRequestSortBy *string) *GetNetworkSubnetsParams {
	o.SetPageRequestSortBy(pageRequestSortBy)
	return o
}

// SetPageRequestSortBy adds the pageRequestSortBy to the get network subnets params
func (o *GetNetworkSubnetsParams) SetPageRequestSortBy(pageRequestSortBy *string) {
	o.PageRequestSortBy = pageRequestSortBy
}

// WithStackID adds the stackID to the get network subnets params
func (o *GetNetworkSubnetsParams) WithStackID(stackID string) *GetNetworkSubnetsParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get network subnets params
func (o *GetNetworkSubnetsParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkSubnetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param network_id
	if err := r.SetPathParam("network_id", o.NetworkID); err != nil {
		return err
	}

	if o.PageRequestAfter != nil {

		// query param page_request.after
		var qrPageRequestAfter string

		if o.PageRequestAfter != nil {
			qrPageRequestAfter = *o.PageRequestAfter
		}
		qPageRequestAfter := qrPageRequestAfter
		if qPageRequestAfter != "" {

			if err := r.SetQueryParam("page_request.after", qPageRequestAfter); err != nil {
				return err
			}
		}
	}

	if o.PageRequestFilter != nil {

		// query param page_request.filter
		var qrPageRequestFilter string

		if o.PageRequestFilter != nil {
			qrPageRequestFilter = *o.PageRequestFilter
		}
		qPageRequestFilter := qrPageRequestFilter
		if qPageRequestFilter != "" {

			if err := r.SetQueryParam("page_request.filter", qPageRequestFilter); err != nil {
				return err
			}
		}
	}

	if o.PageRequestFirst != nil {

		// query param page_request.first
		var qrPageRequestFirst string

		if o.PageRequestFirst != nil {
			qrPageRequestFirst = *o.PageRequestFirst
		}
		qPageRequestFirst := qrPageRequestFirst
		if qPageRequestFirst != "" {

			if err := r.SetQueryParam("page_request.first", qPageRequestFirst); err != nil {
				return err
			}
		}
	}

	if o.PageRequestSortBy != nil {

		// query param page_request.sort_by
		var qrPageRequestSortBy string

		if o.PageRequestSortBy != nil {
			qrPageRequestSortBy = *o.PageRequestSortBy
		}
		qPageRequestSortBy := qrPageRequestSortBy
		if qPageRequestSortBy != "" {

			if err := r.SetQueryParam("page_request.sort_by", qPageRequestSortBy); err != nil {
				return err
			}
		}
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
