// Code generated by go-swagger; DO NOT EDIT.

package workload_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1AllocationClaimStatus v1 allocation claim status
//
// swagger:model v1AllocationClaimStatus
type V1AllocationClaimStatus struct {

	// allocation
	Allocation string `json:"allocation,omitempty"`

	// conditions
	Conditions []*V1Condition `json:"conditions"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// resource binding
	ResourceBinding *V1TypedResourceReference `json:"resourceBinding,omitempty"`
}

// Validate validates this v1 allocation claim status
func (m *V1AllocationClaimStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConditions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceBinding(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AllocationClaimStatus) validateConditions(formats strfmt.Registry) error {
	if swag.IsZero(m.Conditions) { // not required
		return nil
	}

	for i := 0; i < len(m.Conditions); i++ {
		if swag.IsZero(m.Conditions[i]) { // not required
			continue
		}

		if m.Conditions[i] != nil {
			if err := m.Conditions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("conditions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1AllocationClaimStatus) validateResourceBinding(formats strfmt.Registry) error {
	if swag.IsZero(m.ResourceBinding) { // not required
		return nil
	}

	if m.ResourceBinding != nil {
		if err := m.ResourceBinding.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resourceBinding")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 allocation claim status based on the context it is used
func (m *V1AllocationClaimStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConditions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResourceBinding(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AllocationClaimStatus) contextValidateConditions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Conditions); i++ {

		if m.Conditions[i] != nil {
			if err := m.Conditions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("conditions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1AllocationClaimStatus) contextValidateResourceBinding(ctx context.Context, formats strfmt.Registry) error {

	if m.ResourceBinding != nil {
		if err := m.ResourceBinding.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resourceBinding")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1AllocationClaimStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AllocationClaimStatus) UnmarshalBinary(b []byte) error {
	var res V1AllocationClaimStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
