// Code generated by go-swagger; DO NOT EDIT.

package allocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllocationParams creates a new GetAllocationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllocationParams() *GetAllocationParams {
	return &GetAllocationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllocationParamsWithTimeout creates a new GetAllocationParams object
// with the ability to set a timeout on a request.
func NewGetAllocationParamsWithTimeout(timeout time.Duration) *GetAllocationParams {
	return &GetAllocationParams{
		timeout: timeout,
	}
}

// NewGetAllocationParamsWithContext creates a new GetAllocationParams object
// with the ability to set a context for a request.
func NewGetAllocationParamsWithContext(ctx context.Context) *GetAllocationParams {
	return &GetAllocationParams{
		Context: ctx,
	}
}

// NewGetAllocationParamsWithHTTPClient creates a new GetAllocationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllocationParamsWithHTTPClient(client *http.Client) *GetAllocationParams {
	return &GetAllocationParams{
		HTTPClient: client,
	}
}

/*
GetAllocationParams contains all the parameters to send to the API endpoint

	for the get allocation operation.

	Typically these are written to a http.Request.
*/
type GetAllocationParams struct {

	// AllocationSlug.
	AllocationSlug string

	// StackID.
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get allocation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllocationParams) WithDefaults() *GetAllocationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get allocation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllocationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get allocation params
func (o *GetAllocationParams) WithTimeout(timeout time.Duration) *GetAllocationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get allocation params
func (o *GetAllocationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get allocation params
func (o *GetAllocationParams) WithContext(ctx context.Context) *GetAllocationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get allocation params
func (o *GetAllocationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get allocation params
func (o *GetAllocationParams) WithHTTPClient(client *http.Client) *GetAllocationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get allocation params
func (o *GetAllocationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAllocationSlug adds the allocationSlug to the get allocation params
func (o *GetAllocationParams) WithAllocationSlug(allocationSlug string) *GetAllocationParams {
	o.SetAllocationSlug(allocationSlug)
	return o
}

// SetAllocationSlug adds the allocationSlug to the get allocation params
func (o *GetAllocationParams) SetAllocationSlug(allocationSlug string) {
	o.AllocationSlug = allocationSlug
}

// WithStackID adds the stackID to the get allocation params
func (o *GetAllocationParams) WithStackID(stackID string) *GetAllocationParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get allocation params
func (o *GetAllocationParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllocationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param allocation_slug
	if err := r.SetPathParam("allocation_slug", o.AllocationSlug); err != nil {
		return err
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
