// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNetworkPoliciesParams creates a new GetNetworkPoliciesParams object
// with the default values initialized.
func NewGetNetworkPoliciesParams() *GetNetworkPoliciesParams {
	var ()
	return &GetNetworkPoliciesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkPoliciesParamsWithTimeout creates a new GetNetworkPoliciesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNetworkPoliciesParamsWithTimeout(timeout time.Duration) *GetNetworkPoliciesParams {
	var ()
	return &GetNetworkPoliciesParams{

		timeout: timeout,
	}
}

// NewGetNetworkPoliciesParamsWithContext creates a new GetNetworkPoliciesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNetworkPoliciesParamsWithContext(ctx context.Context) *GetNetworkPoliciesParams {
	var ()
	return &GetNetworkPoliciesParams{

		Context: ctx,
	}
}

// NewGetNetworkPoliciesParamsWithHTTPClient creates a new GetNetworkPoliciesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNetworkPoliciesParamsWithHTTPClient(client *http.Client) *GetNetworkPoliciesParams {
	var ()
	return &GetNetworkPoliciesParams{
		HTTPClient: client,
	}
}

/*GetNetworkPoliciesParams contains all the parameters to send to the API endpoint
for the get network policies operation typically these are written to a http.Request
*/
type GetNetworkPoliciesParams struct {

	/*PageRequestAfter
	  The cursor value after which data will be returned.

	*/
	PageRequestAfter *string
	/*PageRequestFilter
	  SQL-style constraint filters.

	*/
	PageRequestFilter *string
	/*PageRequestFirst
	  The number of items desired.

	*/
	PageRequestFirst *string
	/*PageRequestSortBy
	  Sort the response by the given field.

	*/
	PageRequestSortBy *string
	/*StackID
	  The ID of the stack to retrieve network policies from

	*/
	StackID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get network policies params
func (o *GetNetworkPoliciesParams) WithTimeout(timeout time.Duration) *GetNetworkPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network policies params
func (o *GetNetworkPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network policies params
func (o *GetNetworkPoliciesParams) WithContext(ctx context.Context) *GetNetworkPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network policies params
func (o *GetNetworkPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network policies params
func (o *GetNetworkPoliciesParams) WithHTTPClient(client *http.Client) *GetNetworkPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network policies params
func (o *GetNetworkPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPageRequestAfter adds the pageRequestAfter to the get network policies params
func (o *GetNetworkPoliciesParams) WithPageRequestAfter(pageRequestAfter *string) *GetNetworkPoliciesParams {
	o.SetPageRequestAfter(pageRequestAfter)
	return o
}

// SetPageRequestAfter adds the pageRequestAfter to the get network policies params
func (o *GetNetworkPoliciesParams) SetPageRequestAfter(pageRequestAfter *string) {
	o.PageRequestAfter = pageRequestAfter
}

// WithPageRequestFilter adds the pageRequestFilter to the get network policies params
func (o *GetNetworkPoliciesParams) WithPageRequestFilter(pageRequestFilter *string) *GetNetworkPoliciesParams {
	o.SetPageRequestFilter(pageRequestFilter)
	return o
}

// SetPageRequestFilter adds the pageRequestFilter to the get network policies params
func (o *GetNetworkPoliciesParams) SetPageRequestFilter(pageRequestFilter *string) {
	o.PageRequestFilter = pageRequestFilter
}

// WithPageRequestFirst adds the pageRequestFirst to the get network policies params
func (o *GetNetworkPoliciesParams) WithPageRequestFirst(pageRequestFirst *string) *GetNetworkPoliciesParams {
	o.SetPageRequestFirst(pageRequestFirst)
	return o
}

// SetPageRequestFirst adds the pageRequestFirst to the get network policies params
func (o *GetNetworkPoliciesParams) SetPageRequestFirst(pageRequestFirst *string) {
	o.PageRequestFirst = pageRequestFirst
}

// WithPageRequestSortBy adds the pageRequestSortBy to the get network policies params
func (o *GetNetworkPoliciesParams) WithPageRequestSortBy(pageRequestSortBy *string) *GetNetworkPoliciesParams {
	o.SetPageRequestSortBy(pageRequestSortBy)
	return o
}

// SetPageRequestSortBy adds the pageRequestSortBy to the get network policies params
func (o *GetNetworkPoliciesParams) SetPageRequestSortBy(pageRequestSortBy *string) {
	o.PageRequestSortBy = pageRequestSortBy
}

// WithStackID adds the stackID to the get network policies params
func (o *GetNetworkPoliciesParams) WithStackID(stackID string) *GetNetworkPoliciesParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get network policies params
func (o *GetNetworkPoliciesParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PageRequestAfter != nil {

		// query param page_request.after
		var qrPageRequestAfter string
		if o.PageRequestAfter != nil {
			qrPageRequestAfter = *o.PageRequestAfter
		}
		qPageRequestAfter := qrPageRequestAfter
		if qPageRequestAfter != "" {
			if err := r.SetQueryParam("page_request.after", qPageRequestAfter); err != nil {
				return err
			}
		}

	}

	if o.PageRequestFilter != nil {

		// query param page_request.filter
		var qrPageRequestFilter string
		if o.PageRequestFilter != nil {
			qrPageRequestFilter = *o.PageRequestFilter
		}
		qPageRequestFilter := qrPageRequestFilter
		if qPageRequestFilter != "" {
			if err := r.SetQueryParam("page_request.filter", qPageRequestFilter); err != nil {
				return err
			}
		}

	}

	if o.PageRequestFirst != nil {

		// query param page_request.first
		var qrPageRequestFirst string
		if o.PageRequestFirst != nil {
			qrPageRequestFirst = *o.PageRequestFirst
		}
		qPageRequestFirst := qrPageRequestFirst
		if qPageRequestFirst != "" {
			if err := r.SetQueryParam("page_request.first", qPageRequestFirst); err != nil {
				return err
			}
		}

	}

	if o.PageRequestSortBy != nil {

		// query param page_request.sort_by
		var qrPageRequestSortBy string
		if o.PageRequestSortBy != nil {
			qrPageRequestSortBy = *o.PageRequestSortBy
		}
		qPageRequestSortBy := qrPageRequestSortBy
		if qPageRequestSortBy != "" {
			if err := r.SetQueryParam("page_request.sort_by", qPageRequestSortBy); err != nil {
				return err
			}
		}

	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
