// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStackMetricsParams creates a new GetStackMetricsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStackMetricsParams() *GetStackMetricsParams {
	return &GetStackMetricsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStackMetricsParamsWithTimeout creates a new GetStackMetricsParams object
// with the ability to set a timeout on a request.
func NewGetStackMetricsParamsWithTimeout(timeout time.Duration) *GetStackMetricsParams {
	return &GetStackMetricsParams{
		timeout: timeout,
	}
}

// NewGetStackMetricsParamsWithContext creates a new GetStackMetricsParams object
// with the ability to set a context for a request.
func NewGetStackMetricsParamsWithContext(ctx context.Context) *GetStackMetricsParams {
	return &GetStackMetricsParams{
		Context: ctx,
	}
}

// NewGetStackMetricsParamsWithHTTPClient creates a new GetStackMetricsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStackMetricsParamsWithHTTPClient(client *http.Client) *GetStackMetricsParams {
	return &GetStackMetricsParams{
		HTTPClient: client,
	}
}

/* GetStackMetricsParams contains all the parameters to send to the API endpoint
   for the get stack metrics operation.

   Typically these are written to a http.Request.
*/
type GetStackMetricsParams struct {

	/* EndTime.

	   The end date for the range of metrics.

	   Format: date-time
	*/
	EndTime *strfmt.DateTime

	/* StackID.

	   The ID for the stack to collect metrics on
	*/
	StackID string

	/* StartTime.

	   The start date for the range of metrics.

	   Format: date-time
	*/
	StartTime *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get stack metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStackMetricsParams) WithDefaults() *GetStackMetricsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get stack metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStackMetricsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get stack metrics params
func (o *GetStackMetricsParams) WithTimeout(timeout time.Duration) *GetStackMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stack metrics params
func (o *GetStackMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stack metrics params
func (o *GetStackMetricsParams) WithContext(ctx context.Context) *GetStackMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stack metrics params
func (o *GetStackMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stack metrics params
func (o *GetStackMetricsParams) WithHTTPClient(client *http.Client) *GetStackMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stack metrics params
func (o *GetStackMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndTime adds the endTime to the get stack metrics params
func (o *GetStackMetricsParams) WithEndTime(endTime *strfmt.DateTime) *GetStackMetricsParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get stack metrics params
func (o *GetStackMetricsParams) SetEndTime(endTime *strfmt.DateTime) {
	o.EndTime = endTime
}

// WithStackID adds the stackID to the get stack metrics params
func (o *GetStackMetricsParams) WithStackID(stackID string) *GetStackMetricsParams {
	o.SetStackID(stackID)
	return o
}

// SetStackID adds the stackId to the get stack metrics params
func (o *GetStackMetricsParams) SetStackID(stackID string) {
	o.StackID = stackID
}

// WithStartTime adds the startTime to the get stack metrics params
func (o *GetStackMetricsParams) WithStartTime(startTime *strfmt.DateTime) *GetStackMetricsParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get stack metrics params
func (o *GetStackMetricsParams) SetStartTime(startTime *strfmt.DateTime) {
	o.StartTime = startTime
}

// WriteToRequest writes these params to a swagger request
func (o *GetStackMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EndTime != nil {

		// query param end_time
		var qrEndTime strfmt.DateTime

		if o.EndTime != nil {
			qrEndTime = *o.EndTime
		}
		qEndTime := qrEndTime.String()
		if qEndTime != "" {

			if err := r.SetQueryParam("end_time", qEndTime); err != nil {
				return err
			}
		}
	}

	// path param stack_id
	if err := r.SetPathParam("stack_id", o.StackID); err != nil {
		return err
	}

	if o.StartTime != nil {

		// query param start_time
		var qrStartTime strfmt.DateTime

		if o.StartTime != nil {
			qrStartTime = *o.StartTime
		}
		qStartTime := qrStartTime.String()
		if qStartTime != "" {

			if err := r.SetQueryParam("start_time", qStartTime); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
