// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new metrics API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for metrics API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetBucketMetrics(params *GetBucketMetricsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBucketMetricsOK, error)

	GetStackMetrics(params *GetStackMetricsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetStackMetricsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	GetBucketMetrics gets all daily utilizations for specific bucket

	When the start & end dates are not provided, the metrics for the last day will be returned.

The date range used must be at least a day apart, and only beginning times are allowed (e.g. 2019-01-01T00:00:00)
*/
func (a *Client) GetBucketMetrics(params *GetBucketMetricsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBucketMetricsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBucketMetricsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetBucketMetrics",
		Method:             "GET",
		PathPattern:        "/storage/v1/stacks/{stack_id}/buckets/{bucket_id}/metrics",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetBucketMetricsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBucketMetricsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetBucketMetricsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
	GetStackMetrics gets all daily utilizations for all buckets on a stack

	When the start & end dates are not provided, the metrics for the last day will be returned.

The date range used must be at least a day apart, and only beginning times are allowed (e.g. 2019-01-01T00:00:00)
*/
func (a *Client) GetStackMetrics(params *GetStackMetricsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetStackMetricsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetStackMetricsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetStackMetrics",
		Method:             "GET",
		PathPattern:        "/storage/v1/stacks/{stack_id}/metrics",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetStackMetricsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetStackMetricsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetStackMetricsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
