/*
 * Object Storage
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_client

// InlineResponse2003 A response of the updated bucket
type InlineResponse2003 struct {
	Bucket InlineResponse200Results `json:"bucket,omitempty"`
}
