/*
 * Object Storage
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_client

// StackpathRpcQuotaFailure struct for StackpathRpcQuotaFailure
type StackpathRpcQuotaFailure struct {
	Type       string                                    `json:"@type"`
	Violations []StackpathRpcQuotaFailureAllOfViolations `json:"violations,omitempty"`
}
