/*
 * Object Storage
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_client

// PaginationPageRequest Pagination request information  This is modeled after the GraphQL Relay spec to support both cursor based pagination and traditional offset based pagination.
type PaginationPageRequest struct {
	// The number of items desired
	First string `json:"first,omitempty"`
	// The cursor value after which data will be returned
	After string `json:"after,omitempty"`
	// SQL-style constraint filters
	Filter string `json:"filter,omitempty"`
	// Sort the response by the given field
	SortBy string `json:"sortBy,omitempty"`
}
