/*
 * Object Storage
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api_client

// StackpathRpcPreconditionFailureAllOf struct for StackpathRpcPreconditionFailureAllOf
type StackpathRpcPreconditionFailureAllOf struct {
	Violations []StackpathRpcPreconditionFailureAllOfViolations `json:"violations,omitempty"`
}
