// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetBucketMetricsOKBodyData The data points in a metrics collection
// swagger:model getBucketMetricsOKBodyData
type GetBucketMetricsOKBodyData struct {

	// matrix
	Matrix *GetBucketMetricsOKBodyDataMatrix `json:"matrix,omitempty"`

	// vector
	Vector *GetBucketMetricsOKBodyDataVector `json:"vector,omitempty"`
}

// Validate validates this get bucket metrics o k body data
func (m *GetBucketMetricsOKBodyData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMatrix(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVector(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetBucketMetricsOKBodyData) validateMatrix(formats strfmt.Registry) error {

	if swag.IsZero(m.Matrix) { // not required
		return nil
	}

	if m.Matrix != nil {
		if err := m.Matrix.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("matrix")
			}
			return err
		}
	}

	return nil
}

func (m *GetBucketMetricsOKBodyData) validateVector(formats strfmt.Registry) error {

	if swag.IsZero(m.Vector) { // not required
		return nil
	}

	if m.Vector != nil {
		if err := m.Vector.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vector")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetBucketMetricsOKBodyData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetBucketMetricsOKBodyData) UnmarshalBinary(b []byte) error {
	var res GetBucketMetricsOKBodyData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
