// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"
	"io"
	"io/ioutil"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// GetCredentialsInternalServerErrorBodyDetailsItems get credentials internal server error body details items
// swagger:discriminator getCredentialsInternalServerErrorBodyDetailsItems @type
type GetCredentialsInternalServerErrorBodyDetailsItems interface {
	runtime.Validatable

	// at type
	// Required: true
	AtType() string
	SetAtType(string)
}

type getCredentialsInternalServerErrorBodyDetailsItems struct {
	atTypeField string
}

// AtType gets the at type of this polymorphic type
func (m *getCredentialsInternalServerErrorBodyDetailsItems) AtType() string {
	return "getCredentialsInternalServerErrorBodyDetailsItems"
}

// SetAtType sets the at type of this polymorphic type
func (m *getCredentialsInternalServerErrorBodyDetailsItems) SetAtType(val string) {

}

// UnmarshalGetCredentialsInternalServerErrorBodyDetailsItemsSlice unmarshals polymorphic slices of GetCredentialsInternalServerErrorBodyDetailsItems
func UnmarshalGetCredentialsInternalServerErrorBodyDetailsItemsSlice(reader io.Reader, consumer runtime.Consumer) ([]GetCredentialsInternalServerErrorBodyDetailsItems, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []GetCredentialsInternalServerErrorBodyDetailsItems
	for _, element := range elements {
		obj, err := unmarshalGetCredentialsInternalServerErrorBodyDetailsItems(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalGetCredentialsInternalServerErrorBodyDetailsItems unmarshals polymorphic GetCredentialsInternalServerErrorBodyDetailsItems
func UnmarshalGetCredentialsInternalServerErrorBodyDetailsItems(reader io.Reader, consumer runtime.Consumer) (GetCredentialsInternalServerErrorBodyDetailsItems, error) {
	// we need to read this twice, so first into a buffer
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalGetCredentialsInternalServerErrorBodyDetailsItems(data, consumer)
}

func unmarshalGetCredentialsInternalServerErrorBodyDetailsItems(data []byte, consumer runtime.Consumer) (GetCredentialsInternalServerErrorBodyDetailsItems, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the @type property.
	var getType struct {
		AtType string `json:"@type"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("@type", "body", getType.AtType); err != nil {
		return nil, err
	}

	// The value of @type is used to determine which type to create and unmarshal the data into
	switch getType.AtType {
	case "getCredentialsInternalServerErrorBodyDetailsItems":
		var result getCredentialsInternalServerErrorBodyDetailsItems
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil

	}
	return nil, errors.New(422, "invalid @type value: %q", getType.AtType)

}

// Validate validates this get credentials internal server error body details items
func (m *getCredentialsInternalServerErrorBodyDetailsItems) Validate(formats strfmt.Registry) error {
	return nil
}
