// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StackpathRPCHelpAllOf1LinksItems stackpath Rpc help all of1 links items
// swagger:model stackpathRpcHelpAllOf1LinksItems
type StackpathRPCHelpAllOf1LinksItems struct {

	// description
	Description string `json:"description,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this stackpath Rpc help all of1 links items
func (m *StackpathRPCHelpAllOf1LinksItems) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StackpathRPCHelpAllOf1LinksItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StackpathRPCHelpAllOf1LinksItems) UnmarshalBinary(b []byte) error {
	var res StackpathRPCHelpAllOf1LinksItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
